name: period_journey
description: "Period Journey - track your cycle with care."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_riverpod: 2.5.1
  firebase_core: 3.7.0
  cloud_firestore: 5.4.4
  firebase_auth: 5.3.2
  google_sign_in: 6.2.1
  intl: 0.20.2
  shared_preferences: 2.3.2
  table_calendar: 3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:
  uses-material-design: true
